### PR TITLE
fix TiDB DEFAULT_GENERATED

### LINKED ISSUE #289: gravity全量同步时updated_at会发生改变
gravity mysql->tidb 全量+增量同步 时updated_at字段的数据会发生改变，变成当前时间 (测试的比当前时间小8小时 是因为这边k8s时区问题）

batch模式下也存在这个问题，用的最新的版本gravity0.9.71

表结构
图片

mysql的数据
图片

同步后tidb的数据
图片

模式配置
图片

### PR DESCRIPTION
**Pull request by Ryan-Git**
this closes #289 

for datetime column with `DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` property, TiDB show it as `DEFAULT_GENERATED on update CURRENT_TIMESTAMP` in meta data. There might be other cases I'm not sure but anyway  it must be distinguished from MySQL `STORED GENERATED` and `VIRTUAL GENERATED` columns.

### CODE REVIEW

File: pkg/schema_store/utils.go [hunk 1]
```diff
@@ -178,7 +178,10 @@ func GetTableDefFromDB(db *sql.DB, dbName string, tableName string) (*Table, err
 		} else {
 			column.IsPrimaryKey = false
 		}
-		if extra.Valid && strings.Contains(strings.ToUpper(extra.String), "GENERATED") {
+
+		// TiDB describes certain column as `DEFAULT_GENERATED`
+		if extra.Valid && (strings.Contains(strings.ToUpper(extra.String), "VIRTUAL GENERATED") ||
```
Comment (ming535) [inline pkg/schema_store/utils.go:183]: better to cache the result of "IsTidb" , and use that to identiry tidb.

**Review by ming535 — APPROVED** [review]

File: pkg/schema_store/utils.go (hunk 1 above)
Comment (Ryan-Git) [reply pkg/schema_store/utils.go:183]: `IsTiDB` does not help here. 
It distinguishes whether a column is generated or not, rather than TiDB or not.
